app = 'cmpt453project'
primary_region = 'ord'

[build]
dockerfile = "Dockerfile"


[[mounts]]
  source = "client_performance"
  destination = "/data"
  processes = ["app"]

[[services]]
  internal_port = 12345
  protocol = "tcp"

  [[services.ports]]
    port = "12345"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
