app = 'cmpt453project'
primary_region = 'ord'


[[services]]
  internal_port = 12345
  protocol = "tcp"

  [[services.ports]]
    port = "12345"


  [[services.ports]]
    handlers = ["http"]
    port = "80"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
